name: Report bugs
description: Problems encountered in feedback
labels: [bug]
title: "[Bug] Please briefly describe the BUG, otherwise the Issue will be closed directly"
body:
  - type: markdown
    attributes:
      value: |
        In order for us to help you better, please provide the following information.
  - type: textarea
    id: desc
    attributes:
      label: Problem Description
      description: What happened? What's the status quo?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: expected behavior
      description: What should happen normally
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: actual behavior
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: screenshot or screen recording
      description: Screenshots or screen recordings when the problem recurs
      placeholder: Click the small strip below the text box to upload the file
  - type: input
    id: star-ver
    attributes:
      label: Honkai-Star-Rail version
      placeholder: 2.7_test
    validations:
      required: true
  - type: dropdown
    id: server
    attributes:
      label: Honkai Star Server
      options:
        - 国服
        - Global
      description: Currently mainly adapted to Chinese
    validations:
      required: true
  - type: dropdown
    id: equipment
    attributes:
      label: What equipment do you work on?
      options:
        - PC
        - 模拟器
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: log
      description: The logs are in the logs folder.
      placeholder: Click the small strip below the text box to upload the file
    validations:
      required: true