name: feature request
description: Want to request a feature be added
labels: [enhancement]
title: "[Feature] Please briefly describe the Feature, otherwise the Issue will be closed directly"
body:
  - type: textarea
    id: reason
    attributes:
      label: reason
      description: why do you want this feature
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Brief description of functions
      description: what kind of function do you want
    validations:
      required: true
  - type: textarea
    id: logic
    attributes:
      label: functional logic
      description: How to interact, how to use, etc.
    validations:
      required: true
  - type: textarea
    id: ref
    attributes:
      label: implementation reference
      description: The possible implementation of this function, or other applications that have already implemented this function, etc.
