name: 路线异常
description: 自动导航未按正常路线走
labels: [路线错误]
title: "[路线错误] Please enter the map name or number, otherwise the Issue will be closed directly"
body:
  - type: textarea
    id: bug
    attributes:
      label: 问题描述
      description: 说明你遇到的路线问题
    validations:
      required: true
  - type: checkboxes
    id: role
    attributes:
      label: 是否使用三月七跑图
      description: 未使用三月七跑图的反馈不会别受理
      options:
        - label: 是
        - label: 否
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 日志在logs文件夹下。
      placeholder: 点击文本框下面小长条可以上传文件
    validations:
      required: true
